# ::: Code Generated by Copilot [c7d4e5f6-8a9b-4c0d-e1f2-3a4b5c6d7e8f]. This comment will be removed automatically after the file is saved :::
"""
FastAPI application entry point.

Routes
------
GET  /                            Render the input form.
POST /generate                    Parse form, generate drafts, create session.
GET  /review/{session_id}         Render the per-platform review page.
POST /regenerate                  Regenerate a single platform draft (JSON, AJAX).
POST /sync-draft                  Sync an edited textarea back to the session (JSON, AJAX).
POST /schedule                    Schedule a platform's draft (JSON, AJAX).
GET  /history                     Post history dashboard.
"""

from __future__ import annotations

import logging
import secrets
import threading
import uuid
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Annotated
from urllib.parse import urlencode

import requests
from fastapi import FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.templating import Jinja2Templates

from config import settings
from models.schemas import (
    Platform,
    PlatformDraft,
    RegenerateRequest,
    ScheduleRequest,
    ScheduleResult,
)
from platforms.base import Platform as BasePlatform
from platforms.linkedin import LinkedInPlatform
from platforms.reddit import RedditPlatform
from services import linkedin_auth
from services.linkedin_upload import upload_image, upload_document
from services.post_generator import generate_drafts, regenerate_draft
from services.scheduler import scheduler
from services.subreddit_suggester import suggest_subreddits
from services.database import create_post_record, init_db, list_post_records

# ── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

# ── Platform registry ──────────────────────────────────────────────────────────
# To add a new platform: instantiate it here and add it to this dict.
PLATFORM_REGISTRY: dict[str, BasePlatform] = {
    Platform.LINKEDIN.value: LinkedInPlatform(),
    Platform.REDDIT.value: RedditPlatform(),
}


# ── Session store (in-memory) ──────────────────────────────────────────────────
@dataclass
class SessionData:
    """Holds all state for one drafting session."""

    drafts: dict[str, PlatformDraft]  # keyed by Platform.value
    suggested_subreddits: list[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    last_accessed: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def touch(self) -> None:
        """Update the last-accessed timestamp."""
        self.last_accessed = datetime.now(timezone.utc)


_sessions: dict[str, SessionData] = {}
_sessions_lock = threading.Lock()


def _create_session(
    drafts: list[PlatformDraft],
    suggested_subreddits: list[str] | None = None,
) -> str:
    """Store drafts (and optional subreddit suggestions) in a new session.

    Returns the session ID.
    """
    session_id = str(uuid.uuid4())
    data = SessionData(
        drafts={d.platform.value: d for d in drafts},
        suggested_subreddits=suggested_subreddits or [],
    )
    with _sessions_lock:
        _sessions[session_id] = data
    return session_id


def _get_session(session_id: str) -> SessionData:
    """Retrieve a session, updating its last-accessed time.

    Raises:
        HTTPException 404: If the session does not exist or has expired.
    """
    with _sessions_lock:
        session = _sessions.get(session_id)
    if session is None:
        raise HTTPException(status_code=404, detail="Session not found or expired.")
    session.touch()
    return session


def _evict_expired_sessions() -> None:
    """Remove sessions older than SESSION_TTL_MINUTES. Called by APScheduler."""
    cutoff = datetime.now(timezone.utc) - timedelta(minutes=settings.session_ttl_minutes)
    with _sessions_lock:
        expired = [sid for sid, s in _sessions.items() if s.last_accessed < cutoff]
        for sid in expired:
            del _sessions[sid]
    if expired:
        logger.info("Evicted %d expired session(s).", len(expired))


# ── App lifespan ───────────────────────────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):  # noqa: ARG001
    """Start APScheduler and init the database on startup; stop on shutdown."""
    init_db()
    linkedin_auth.load_token()
    scheduler.add_job(
        _evict_expired_sessions,
        trigger="interval",
        minutes=30,
        id="session_eviction",
        replace_existing=True,
    )
    scheduler.start()
    logger.info("APScheduler started.")
    yield
    scheduler.shutdown(wait=False)
    logger.info("APScheduler stopped.")


# ── FastAPI app ────────────────────────────────────────────────────────────────
app = FastAPI(title="AI Digital Marketer", lifespan=lifespan)
templates = Jinja2Templates(directory="templates")


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse)
async def index(request: Request) -> HTMLResponse:
    """Render the input form."""
    return templates.TemplateResponse(
        "index.html",
        {
            "request": request,
            "linkedin_connected": linkedin_auth.is_connected(),
            "linkedin_expires_at": linkedin_auth.token_expires_at(),
        },
    )


# ── LinkedIn OAuth 2.0 ─────────────────────────────────────────────────────────

@app.get("/auth/linkedin")
async def auth_linkedin_start() -> RedirectResponse:
    """Redirect the user to LinkedIn's OAuth 2.0 consent screen."""
    if not settings.linkedin_client_id:
        raise HTTPException(
            status_code=500,
            detail="LINKEDIN_CLIENT_ID is not configured.",
        )
    state = secrets.token_urlsafe(24)
    linkedin_auth.set_pending_state(state)
    params = urlencode({
        "response_type": "code",
        "client_id": settings.linkedin_client_id,
        "redirect_uri": settings.linkedin_redirect_uri,
        "state": state,
        "scope": "openid profile w_member_social",
    })
    return RedirectResponse(
        f"https://www.linkedin.com/oauth/v2/authorization?{params}"
    )


@app.get("/auth/linkedin/callback", response_class=HTMLResponse)
async def auth_linkedin_callback(
    request: Request,
    code: str = "",
    state: str = "",
    error: str = "",
    error_description: str = "",
) -> RedirectResponse:
    """Handle LinkedIn's OAuth callback, exchange code for token, store it."""
    if error:
        logger.warning("LinkedIn OAuth denied: %s — %s", error, error_description)
        return RedirectResponse("/?linkedin_error=1")

    expected_state = linkedin_auth.consume_pending_state()
    if not expected_state or state != expected_state:
        raise HTTPException(status_code=400, detail="Invalid OAuth state parameter.")

    if not code:
        raise HTTPException(status_code=400, detail="Missing authorization code.")

    # Exchange code for access token
    token_resp = requests.post(
        "https://www.linkedin.com/oauth/v2/accessToken",
        data={
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": settings.linkedin_redirect_uri,
            "client_id": settings.linkedin_client_id,
            "client_secret": settings.linkedin_client_secret,
        },
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        timeout=15,
    )
    if not token_resp.ok:
        logger.error("LinkedIn token exchange failed: %s", token_resp.text)
        raise HTTPException(
            status_code=502,
            detail=f"LinkedIn token exchange failed: {token_resp.status_code}",
        )

    token_data = token_resp.json()
    access_token: str = token_data["access_token"]
    expires_in: int | None = token_data.get("expires_in")

    # Fetch person ID via OpenID userinfo endpoint
    userinfo_resp = requests.get(
        "https://api.linkedin.com/v2/userinfo",
        headers={"Authorization": f"Bearer {access_token}"},
        timeout=10,
    )
    if not userinfo_resp.ok:
        logger.error("LinkedIn userinfo failed: %s", userinfo_resp.text)
        raise HTTPException(
            status_code=502,
            detail="Could not fetch LinkedIn profile after authentication.",
        )

    person_id: str = userinfo_resp.json().get("sub", "")
    if not person_id:
        raise HTTPException(
            status_code=502,
            detail="LinkedIn userinfo did not return a person ID.",
        )

    linkedin_auth.set_token(access_token, person_id, expires_in)
    logger.info("LinkedIn connected — person ID: %s", person_id)
    return RedirectResponse("/?linkedin_connected=1")


@app.get("/auth/linkedin/disconnect")
async def auth_linkedin_disconnect() -> RedirectResponse:
    """Clear the stored LinkedIn token."""
    linkedin_auth.disconnect()
    return RedirectResponse("/")


# ── LinkedIn media upload ──────────────────────────────────────────────────────

# Allowed MIME types for LinkedIn media uploads
_LINKEDIN_IMAGE_MIMES = {"image/jpeg", "image/png", "image/gif"}
_LINKEDIN_DOC_MIMES = {
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",  # docx
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",  # pptx
}
_MAX_IMAGE_BYTES = 5 * 1024 * 1024       # 5 MB
_MAX_DOC_BYTES   = 100 * 1024 * 1024     # 100 MB

@app.post("/upload/linkedin")
async def upload_linkedin_media(
    session_id: Annotated[str, Form()],
    file: UploadFile = File(...),
) -> dict:
    """Upload an image or document to LinkedIn and attach the URN to the session draft.

    The file is uploaded immediately to LinkedIn's asset APIs so the URN is
    available when the post is later scheduled.  The session draft is updated
    in-place with ``media_urn`` and ``media_type``.
    """
    session = _get_session(session_id)

    # Validate LinkedIn is connected
    access_token = linkedin_auth.get_token()
    person_id    = linkedin_auth.get_person_id()
    if not access_token or not person_id:
        raise HTTPException(
            status_code=400,
            detail="LinkedIn is not connected. Visit /auth/linkedin first.",
        )

    mime_type = file.content_type or ""
    file_bytes = await file.read()

    if mime_type in _LINKEDIN_IMAGE_MIMES:
        if len(file_bytes) > _MAX_IMAGE_BYTES:
            raise HTTPException(status_code=413, detail="Image exceeds 5 MB limit.")
        try:
            urn = upload_image(file_bytes, mime_type, person_id, access_token)
        except RuntimeError as exc:
            raise HTTPException(status_code=502, detail=str(exc)) from exc
        media_type = "image"

    elif mime_type in _LINKEDIN_DOC_MIMES:
        if len(file_bytes) > _MAX_DOC_BYTES:
            raise HTTPException(status_code=413, detail="Document exceeds 100 MB limit.")
        try:
            urn = upload_document(file_bytes, file.filename or "document", person_id, access_token)
        except RuntimeError as exc:
            raise HTTPException(status_code=502, detail=str(exc)) from exc
        media_type = "document"

    else:
        raise HTTPException(
            status_code=415,
            detail=f"Unsupported file type '{mime_type}'. "
                   "Allowed: JPEG, PNG, GIF, PDF, DOCX, PPTX.",
        )

    # Attach the URN to the LinkedIn draft in the session
    draft = session.drafts.get(Platform.LINKEDIN.value)
    if draft is None:
        raise HTTPException(
            status_code=404,
            detail="No LinkedIn draft found in this session.",
        )
    session.drafts[Platform.LINKEDIN.value] = draft.model_copy(
        update={"media_urn": urn, "media_type": media_type}
    )

    logger.info(
        "LinkedIn media attached to session %s — type=%s urn=%s",
        session_id, media_type, urn,
    )
    return {"media_urn": urn, "media_type": media_type, "filename": file.filename}


@app.post("/generate", response_class=HTMLResponse)
async def generate(
    request: Request,
    writeup: Annotated[str, Form()],
) -> HTMLResponse:
    """Parse the submitted form, generate drafts for all selected platforms,
    store in a new session, and redirect to the review page.
    """
    form = await request.form()

    # Extract multi-value fields manually (FastAPI Form doesn't auto-collect lists
    # when keys repeat in multipart/form-urlencoded)
    urls: list[str] = [
        v for k, v in form.multi_items() if k == "urls" and v.strip()
    ]
    raw_platforms: list[str] = [
        v for k, v in form.multi_items() if k == "platforms"
    ]

    # Validate platform values
    selected_platforms: list[Platform] = []
    for p in raw_platforms:
        try:
            selected_platforms.append(Platform(p))
        except ValueError:
            logger.warning("Unknown platform in form submission: %s", p)

    if not selected_platforms:
        return templates.TemplateResponse(
            "index.html",
            {
                "request": request,
                "error": "Please select at least one platform.",
            },
            status_code=400,
        )

    # Build the combined input string
    parts = [writeup.strip()]
    if urls:
        parts.append("\nReference URLs:")
        parts.extend(f"- {url}" for url in urls)
    combined_input = "\n".join(parts)

    try:
        drafts = generate_drafts(input_text=combined_input, platforms=selected_platforms)
    except Exception as exc:
        logger.exception("Draft generation failed: %s", exc)
        return templates.TemplateResponse(
            "index.html",
            {
                "request": request,
                "error": f"Failed to generate drafts: {exc}",
            },
            status_code=500,
        )

    # Suggest subreddits when Reddit is among the selected platforms.
    subreddit_suggestions: list[str] = []
    if Platform.REDDIT in selected_platforms:
        try:
            subreddit_suggestions = suggest_subreddits(combined_input)
        except Exception as exc:  # never block the main flow
            logger.warning("Subreddit suggestion skipped: %s", exc)

    session_id = _create_session(drafts, suggested_subreddits=subreddit_suggestions)
    logger.info(
        "Session created: %s (%d drafts, %d subreddit suggestions)",
        session_id, len(drafts), len(subreddit_suggestions),
    )
    return RedirectResponse(url=f"/review/{session_id}", status_code=303)


@app.get("/review/{session_id}", response_class=HTMLResponse)
async def review(request: Request, session_id: str) -> HTMLResponse:
    """Render the review page for a given session."""
    session = _get_session(session_id)
    drafts = list(session.drafts.values())
    # Prefer LLM-suggested subreddits; fall back to configured defaults.
    subreddits = session.suggested_subreddits or settings.reddit_default_subreddits_list
    return templates.TemplateResponse(
        "review.html",
        {
            "request": request,
            "session_id": session_id,
            "drafts": drafts,
            "suggested_subreddits": subreddits,
        },
    )


@app.post("/regenerate")
async def regenerate(body: RegenerateRequest) -> dict:
    """Regenerate a single platform's draft using a follow-up instruction.

    Returns the updated draft content as JSON so the UI can update in place.
    """
    session = _get_session(body.session_id)

    existing = session.drafts.get(body.platform.value)
    existing_draft_content = existing.content if existing else ""

    try:
        updated_draft = regenerate_draft(
            follow_up=body.follow_up,
            platform=body.platform,
            existing_draft=existing_draft_content,
        )
    except Exception as exc:
        logger.exception("Regeneration failed for %s: %s", body.platform.value, exc)
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    # Preserve the previously selected subreddit (if any)
    if existing and existing.subreddit:
        updated_draft = updated_draft.model_copy(update={"subreddit": existing.subreddit})

    session.drafts[body.platform.value] = updated_draft
    logger.info("Draft regenerated for session %s, platform %s", body.session_id, body.platform.value)

    return {"platform": body.platform.value, "content": updated_draft.content}


@app.post("/sync-draft")
async def sync_draft(body: dict) -> dict:
    """Sync the user's edited textarea content back to the server-side session.

    Expected JSON body: { session_id, platform, content }
    Called automatically before scheduling so the final edits are preserved.
    """
    session_id: str = body.get("session_id", "")
    platform_raw: str = body.get("platform", "")
    content: str = body.get("content", "")

    if not session_id or not platform_raw:
        raise HTTPException(status_code=422, detail="session_id and platform are required.")

    try:
        platform = Platform(platform_raw)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=f"Unknown platform: {platform_raw}") from exc

    session = _get_session(session_id)

    existing = session.drafts.get(platform.value)
    if existing is None:
        raise HTTPException(
            status_code=404,
            detail=f"No draft found for platform '{platform.value}' in this session.",
        )

    session.drafts[platform.value] = existing.model_copy(update={"content": content})
    return {"status": "synced"}


@app.post("/schedule")
async def schedule(body: ScheduleRequest) -> ScheduleResult:
    """Schedule the current draft for a platform.

    If body.post_at is provided (UTC ISO-8601) it is used directly.
    Otherwise defaults to now + 24 hours.  The requested time must be at
    least 5 minutes in the future.
    """
    session = _get_session(body.session_id)

    draft = session.drafts.get(body.platform.value)
    if draft is None:
        raise HTTPException(
            status_code=404,
            detail=f"No draft for platform '{body.platform.value}' in this session.",
        )

    # Override subreddit if supplied, then persist back to session
    if body.subreddit:
        draft = draft.model_copy(update={"subreddit": body.subreddit})
        session.drafts[body.platform.value] = draft

    platform_handler = PLATFORM_REGISTRY.get(body.platform.value)
    if platform_handler is None:
        raise HTTPException(
            status_code=400,
            detail=f"Platform '{body.platform.value}' is not configured.",
        )

    now = datetime.now(timezone.utc)

    if body.post_at is not None:
        # Normalise to UTC regardless of what the client sent
        post_at = body.post_at.astimezone(timezone.utc) if body.post_at.tzinfo else body.post_at.replace(tzinfo=timezone.utc)
        min_allowed = now + timedelta(minutes=5)
        if post_at < min_allowed:
            raise HTTPException(
                status_code=422,
                detail="Scheduled time must be at least 5 minutes in the future.",
            )
    else:
        post_at = now + timedelta(hours=24)

    # Persist the record before calling the platform so Reddit's APScheduler
    # job has a valid record_id to update when it fires.
    record_id = create_post_record(
        platform=body.platform.value,
        content=draft.content,
        scheduled_at=post_at,
        subreddit=draft.subreddit,
    )

    try:
        result = platform_handler.schedule(draft=draft, post_at=post_at, record_id=record_id)
    except (ValueError, RuntimeError) as exc:
        logger.exception("Scheduling failed for %s: %s", body.platform.value, exc)
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    logger.info(
        "Scheduled %s for session %s at %s (record_id=%s)",
        body.platform.value,
        body.session_id,
        post_at.isoformat(),
        record_id,
    )
    return result


@app.get("/history", response_class=HTMLResponse)
async def history(request: Request) -> HTMLResponse:
    """Render the post history dashboard."""
    records = list_post_records(limit=200)
    return templates.TemplateResponse(
        "history.html",
        {"request": request, "records": records},
    )
